import discord
import json
import random
import string
from discord.ext import commands

# 1️⃣ Set up the bot
intents = discord.Intents.default()
intents.message_content = True
intents.members = True
bot = commands.Bot(command_prefix="!", intents=intents)

# 2️⃣ JSON file to store keys
KEYS_FILE = "keys.json"

# 3️⃣ Authorized users
AUTHORIZED_USERS = [
    1408091114736713881, 889478731196936212  # Replace with your Discord ID(s)
]

# 4️⃣ Helper functions
def load_keys():
    try:
        with open(KEYS_FILE, "r") as f:
            return json.load(f)
    except FileNotFoundError:
        return {}

def save_keys(keys):
    with open(KEYS_FILE, "w") as f:
        json.dump(keys, f, indent=4)

# 5️⃣ Generate a key for the fixed role
@bot.command()
async def genkey(ctx, member: discord.Member = None):
    await ctx.message.delete()

    if ctx.author.id not in AUTHORIZED_USERS:
        await ctx.send("Not authorized.", delete_after=5)
        return

    role_id = 1439609947586429109  # Fixed role ID
    key = ''.join(random.choices(string.ascii_letters + string.digits, k=20))
    keys = load_keys()
    spoiler_key = f"||{key}||"

    if member is not None:
        keys[key] = {"role_id": role_id, "used": False, "creator": ctx.author.id, "user": member.id}
        await member.send(
            f"User ID: {member.id}\n"
            f"Key generated by: {ctx.author.id}\n"
            f"Your key: {spoiler_key}\n"
            f"Use the command: !redeem {key}\n"
            "Don't share this key with anyone."
        )
        await ctx.send("Sent to user.", delete_after=5)
    else:
        keys[key] = {"role_id": role_id, "used": False, "creator": ctx.author.id, "user": ctx.author.id}
        await ctx.author.send(
            f"User ID: {ctx.author.id}\n"
            f"Key generated by: {ctx.author.id}\n"
            f"Your key: {spoiler_key}\n"
            f"Use the command: !redeem {key}\n"
            "Don't share this key with anyone."
        )
        await ctx.send("Sent to you.", delete_after=5)

    save_keys(keys)

# 6️⃣ Redeem the key
@bot.command()
async def redeem(ctx, key: str):
    await ctx.message.delete()
    keys = load_keys()

    if key not in keys:
        await ctx.send("Invalid key.", delete_after=5)
        return

    key_data = keys[key]
    if key_data["used"]:
        await ctx.send("Key has already been used.", delete_after=5)
        return

    role = ctx.guild.get_role(key_data["role_id"])
    if role:
        await ctx.author.add_roles(role)
        await ctx.author.send(
            f"You have successfully redeemed your key!\n"
            f"Key: ||{key}||\n"
            f"Role assigned: {role.name}"
        )
        await ctx.send("Role assigned.", delete_after=5)
    else:
        await ctx.send("Role not found.", delete_after=5)

    key_data["used"] = True
    key_data["user"] = ctx.author.id
    save_keys(keys)

# 7️⃣ Dump keys as file
@bot.command()
async def dumpkeys(ctx):
    await ctx.message.delete()

    if ctx.author.id not in AUTHORIZED_USERS:
        await ctx.send("Not authorized.", delete_after=5)
        return
    try:
        await ctx.author.send(file=discord.File(KEYS_FILE))
        await ctx.send("Sent.", delete_after=5)
    except FileNotFoundError:
        await ctx.send("No keys.", delete_after=5)

# 8️⃣ Commands list
@bot.command()
async def cmds(ctx):
    await ctx.message.delete()
    await ctx.send(
        "!genkey [@user] - Generate a new key\n"
        "!redeem <key> - Redeem a key\n"
        "!dumpkeys - Get the keys file\n"
        "!keys - Show your keys in DM\n"
        "!check @user - See if a user has keys (authorized only)\n",
        delete_after=10
    )

# 9️⃣ Show all keys for yourself in DM
@bot.command()
async def keys(ctx):
    await ctx.message.delete()
    keys_data = load_keys()
    user_keys = [k for k, v in keys_data.items() if v["user"] == ctx.author.id]

    if not user_keys:
        msg = await ctx.author.send("You have no keys generated.")
    else:
        message_content = "Here are your keys:\n" + "\n".join([f"||{k}|| - Used: {keys_data[k]['used']}" for k in user_keys])
        msg = await ctx.author.send(message_content)

    # Delete the DM after 10 seconds
    await msg.delete(delay=10)

# 🔟 Check if a user has ever been generated a key (authorized only)
@bot.command()
async def check(ctx, member: discord.Member):
    await ctx.message.delete()

    if ctx.author.id not in AUTHORIZED_USERS:
        await ctx.send("Not authorized.", delete_after=10)
        return

    keys_data = load_keys()
    user_keys = [k for k, v in keys_data.items() if v["user"] == member.id]

    if not user_keys:
        msg = await ctx.send(f"{member} has no keys generated.")
    else:
        msg = await ctx.send(f"{member} has {len(user_keys)} key(s) generated.")

    # Delete the bot message after 10 seconds
    await msg.delete(delay=10)

# 🔟 Start the bot
bot.run("MTQzOTYzMjM0NTgzMjQ4ODk4MA.GWKq1W.bu7Y_nm44McDoVeFsKEBVeIPvbD43j_pXjfx6k")  # <-- Replace with your bot token safely